// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice =
  | FeaturedWorksTitleSlice
  | MarqueeSliceSlice
  | WorksShowcaseLeftSlice
  | WorksShowcaseRightSlice
  | ContactShowcaseSlice
  | NewsAndInsightsSlice
  | FeaturedWorksShowCaseSlice
  | HomeBriefSlice
  | HomeHeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PrivacyPolicyDocumentDataSlicesSlice =
  | PrivTextSliceBSlice
  | PrivTextSliceASlice
  | PrivTitleSliceSlice
  | PrivSubTitleSliceSlice
  | PrivTextSliceSlice;

/**
 * Content for Privacy Policy documents
 */
interface PrivacyPolicyDocumentData {
  /**
   * Slice Zone field in *Privacy Policy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PrivacyPolicyDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: privacy_policy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Privacy Policy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Privacy Policy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: privacy_policy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Privacy Policy document from Prismic
 *
 * - **API ID**: `privacy_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyPolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacyPolicyDocumentData>,
    "privacy_policy",
    Lang
  >;

type WorksDocumentDataSlicesSlice =
  | WorksShowcaseLeftSlice
  | WorksShowcaseRightSlice;

/**
 * Content for Works documents
 */
interface WorksDocumentData {
  /**
   * Title field in *Works*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Works*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: works.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WorksDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: works.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Works*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Works*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: works.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Works document from Prismic
 *
 * - **API ID**: `works`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorksDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<WorksDocumentData>, "works", Lang>;

type WorksChildDocumentDataSlicesSlice =
  | NextProjectLinkSlice
  | BehindTheScenesSlice
  | WorkChildImageSlice
  | WorkChildVisionSlice
  | WorkChildBriefSlice
  | WorkChildHeroSlice;

/**
 * Content for Works Child documents
 */
interface WorksChildDocumentData {
  /**
   * Slice Zone field in *Works Child*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: works_child.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WorksChildDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Works Child*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: works_child.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Works Child*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works_child.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Works Child*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: works_child.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Works Child document from Prismic
 *
 * - **API ID**: `works_child`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorksChildDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<WorksChildDocumentData>,
    "works_child",
    Lang
  >;

export type AllDocumentTypes =
  | HomeDocument
  | PrivacyPolicyDocument
  | WorksDocument
  | WorksChildDocument;

/**
 * Primary content in *BehindTheScenes → Primary*
 */
export interface BehindTheScenesSliceDefaultPrimary {
  /**
   * CTA Link field in *BehindTheScenes → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: behind_the_scenes.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Primary content in *BehindTheScenes → Items*
 */
export interface BehindTheScenesSliceDefaultItem {
  /**
   * Image field in *BehindTheScenes → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: behind_the_scenes.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for BehindTheScenes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BehindTheScenesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BehindTheScenesSliceDefaultPrimary>,
  Simplify<BehindTheScenesSliceDefaultItem>
>;

/**
 * Slice variation for *BehindTheScenes*
 */
type BehindTheScenesSliceVariation = BehindTheScenesSliceDefault;

/**
 * BehindTheScenes Shared Slice
 *
 * - **API ID**: `behind_the_scenes`
 * - **Description**: BehindTheScenes
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BehindTheScenesSlice = prismic.SharedSlice<
  "behind_the_scenes",
  BehindTheScenesSliceVariation
>;

/**
 * Primary content in *ContactShowcase → Primary*
 */
export interface ContactShowcaseSliceDefaultPrimary {
  /**
   * Showcase Title field in *ContactShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_showcase.primary.showcase_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  showcase_title: prismic.RichTextField;

  /**
   * Email field in *ContactShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_showcase.primary.email
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  email: prismic.RichTextField;

  /**
   * Phone field in *ContactShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_showcase.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  phone: prismic.RichTextField;

  /**
   * Contact Info Text field in *ContactShowcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_showcase.primary.contact_info_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact_info_text: prismic.RichTextField;

  /**
   * CursorImage field in *ContactShowcase → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_showcase.primary.cursorimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cursorimage: prismic.ImageField<never>;

  /**
   * CTA Link field in *ContactShowcase → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_showcase.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Primary content in *ContactShowcase → Items*
 */
export interface ContactShowcaseSliceDefaultItem {
  /**
   * Contact field in *ContactShowcase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_showcase.items[].contact
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact: prismic.RichTextField;
}

/**
 * Default variation for ContactShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactShowcaseSliceDefaultPrimary>,
  Simplify<ContactShowcaseSliceDefaultItem>
>;

/**
 * Slice variation for *ContactShowcase*
 */
type ContactShowcaseSliceVariation = ContactShowcaseSliceDefault;

/**
 * ContactShowcase Shared Slice
 *
 * - **API ID**: `contact_showcase`
 * - **Description**: ContactShowcase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactShowcaseSlice = prismic.SharedSlice<
  "contact_showcase",
  ContactShowcaseSliceVariation
>;

/**
 * Primary content in *FeaturedWorksShowCase → Primary*
 */
export interface FeaturedWorksShowCaseSliceDefaultPrimary {
  /**
   * Title field in *FeaturedWorksShowCase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_works_show_case.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *FeaturedWorksShowCase → Items*
 */
export interface FeaturedWorksShowCaseSliceDefaultItem {
  /**
   * Company Name field in *FeaturedWorksShowCase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_works_show_case.items[].company_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_name: prismic.RichTextField;

  /**
   * Description field in *FeaturedWorksShowCase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_works_show_case.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *FeaturedWorksShowCase → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_works_show_case.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Work CTA Link field in *FeaturedWorksShowCase → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_works_show_case.items[].work_cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  work_cta_link: prismic.LinkField;
}

/**
 * Default variation for FeaturedWorksShowCase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedWorksShowCaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedWorksShowCaseSliceDefaultPrimary>,
  Simplify<FeaturedWorksShowCaseSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturedWorksShowCase*
 */
type FeaturedWorksShowCaseSliceVariation = FeaturedWorksShowCaseSliceDefault;

/**
 * FeaturedWorksShowCase Shared Slice
 *
 * - **API ID**: `featured_works_show_case`
 * - **Description**: FeaturedWorksShowCase
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedWorksShowCaseSlice = prismic.SharedSlice<
  "featured_works_show_case",
  FeaturedWorksShowCaseSliceVariation
>;

/**
 * Primary content in *FeaturedWorksTitle → Primary*
 */
export interface FeaturedWorksTitleSliceDefaultPrimary {
  /**
   * Title field in *FeaturedWorksTitle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_works_title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for FeaturedWorksTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedWorksTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedWorksTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedWorksTitle*
 */
type FeaturedWorksTitleSliceVariation = FeaturedWorksTitleSliceDefault;

/**
 * FeaturedWorksTitle Shared Slice
 *
 * - **API ID**: `featured_works_title`
 * - **Description**: FeaturedWorksTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedWorksTitleSlice = prismic.SharedSlice<
  "featured_works_title",
  FeaturedWorksTitleSliceVariation
>;

/**
 * Primary content in *HomeBrief → Primary*
 */
export interface HomeBriefSliceDefaultPrimary {
  /**
   * Title field in *HomeBrief → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_brief.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *HomeBrief → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_brief.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for HomeBrief Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeBriefSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeBriefSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeBrief*
 */
type HomeBriefSliceVariation = HomeBriefSliceDefault;

/**
 * HomeBrief Shared Slice
 *
 * - **API ID**: `home_brief`
 * - **Description**: HomeBrief
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeBriefSlice = prismic.SharedSlice<
  "home_brief",
  HomeBriefSliceVariation
>;

/**
 * Primary content in *HomeHero → Primary*
 */
export interface HomeHeroSliceDefaultPrimary {
  /**
   * Title field in *HomeHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeHero*
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: HomeHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSlice = prismic.SharedSlice<
  "home_hero",
  HomeHeroSliceVariation
>;

/**
 * Primary content in *MarqueeSlice → Primary*
 */
export interface MarqueeSliceSliceDefaultPrimary {
  /**
   * Title field in *MarqueeSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *MarqueeSlice → Items*
 */
export interface MarqueeSliceSliceDefaultItem {
  /**
   * Marquee Logo field in *MarqueeSlice → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee_slice.items[].marquee_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  marquee_logo: prismic.ImageField<never>;
}

/**
 * Default variation for MarqueeSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarqueeSliceSliceDefaultPrimary>,
  Simplify<MarqueeSliceSliceDefaultItem>
>;

/**
 * Slice variation for *MarqueeSlice*
 */
type MarqueeSliceSliceVariation = MarqueeSliceSliceDefault;

/**
 * MarqueeSlice Shared Slice
 *
 * - **API ID**: `marquee_slice`
 * - **Description**: MarqueeSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeSliceSlice = prismic.SharedSlice<
  "marquee_slice",
  MarqueeSliceSliceVariation
>;

/**
 * Primary content in *NewsAndInsights → Primary*
 */
export interface NewsAndInsightsSliceDefaultPrimary {
  /**
   * Title field in *NewsAndInsights → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_and_insights.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *NewsAndInsights → Items*
 */
export interface NewsAndInsightsSliceDefaultItem {
  /**
   * Image field in *NewsAndInsights → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news_and_insights.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *NewsAndInsights → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news_and_insights.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * CTA Link field in *NewsAndInsights → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: news_and_insights.items[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for NewsAndInsights Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsAndInsightsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsAndInsightsSliceDefaultPrimary>,
  Simplify<NewsAndInsightsSliceDefaultItem>
>;

/**
 * Slice variation for *NewsAndInsights*
 */
type NewsAndInsightsSliceVariation = NewsAndInsightsSliceDefault;

/**
 * NewsAndInsights Shared Slice
 *
 * - **API ID**: `news_and_insights`
 * - **Description**: NewsAndInsights
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsAndInsightsSlice = prismic.SharedSlice<
  "news_and_insights",
  NewsAndInsightsSliceVariation
>;

/**
 * Primary content in *NextProjectLink → Primary*
 */
export interface NextProjectLinkSliceDefaultPrimary {
  /**
   * CTA Link field in *NextProjectLink → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: next_project_link.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for NextProjectLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NextProjectLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NextProjectLinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NextProjectLink*
 */
type NextProjectLinkSliceVariation = NextProjectLinkSliceDefault;

/**
 * NextProjectLink Shared Slice
 *
 * - **API ID**: `next_project_link`
 * - **Description**: NextProjectLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NextProjectLinkSlice = prismic.SharedSlice<
  "next_project_link",
  NextProjectLinkSliceVariation
>;

/**
 * Primary content in *PrivSubTitleSlice → Primary*
 */
export interface PrivSubTitleSliceSliceDefaultPrimary {
  /**
   * SubTitle field in *PrivSubTitleSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: priv_sub_title_slice.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for PrivSubTitleSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivSubTitleSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrivSubTitleSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrivSubTitleSlice*
 */
type PrivSubTitleSliceSliceVariation = PrivSubTitleSliceSliceDefault;

/**
 * PrivSubTitleSlice Shared Slice
 *
 * - **API ID**: `priv_sub_title_slice`
 * - **Description**: PrivSubTitleSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivSubTitleSliceSlice = prismic.SharedSlice<
  "priv_sub_title_slice",
  PrivSubTitleSliceSliceVariation
>;

/**
 * Primary content in *PrivTextSlice → Primary*
 */
export interface PrivTextSliceSliceDefaultPrimary {
  /**
   * Text field in *PrivTextSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: priv_text_slice.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for PrivTextSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivTextSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrivTextSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrivTextSlice*
 */
type PrivTextSliceSliceVariation = PrivTextSliceSliceDefault;

/**
 * PrivTextSlice Shared Slice
 *
 * - **API ID**: `priv_text_slice`
 * - **Description**: PrivTextSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivTextSliceSlice = prismic.SharedSlice<
  "priv_text_slice",
  PrivTextSliceSliceVariation
>;

/**
 * Primary content in *PrivTextSliceA → Primary*
 */
export interface PrivTextSliceASliceDefaultPrimary {
  /**
   * Title field in *PrivTextSliceA → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: priv_text_slice_a.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *PrivTextSliceA → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: priv_text_slice_a.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for PrivTextSliceA Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivTextSliceASliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrivTextSliceASliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrivTextSliceA*
 */
type PrivTextSliceASliceVariation = PrivTextSliceASliceDefault;

/**
 * PrivTextSliceA Shared Slice
 *
 * - **API ID**: `priv_text_slice_a`
 * - **Description**: PrivTextSliceA
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivTextSliceASlice = prismic.SharedSlice<
  "priv_text_slice_a",
  PrivTextSliceASliceVariation
>;

/**
 * Primary content in *PrivTextSliceB → Primary*
 */
export interface PrivTextSliceBSliceDefaultPrimary {
  /**
   * Title field in *PrivTextSliceB → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: priv_text_slice_b.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * SubText field in *PrivTextSliceB → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: priv_text_slice_b.primary.subtext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtext: prismic.RichTextField;

  /**
   * Bullet Points field in *PrivTextSliceB → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: priv_text_slice_b.primary.bullet_points
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bullet_points: prismic.RichTextField;
}

/**
 * Default variation for PrivTextSliceB Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivTextSliceBSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrivTextSliceBSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrivTextSliceB*
 */
type PrivTextSliceBSliceVariation = PrivTextSliceBSliceDefault;

/**
 * PrivTextSliceB Shared Slice
 *
 * - **API ID**: `priv_text_slice_b`
 * - **Description**: PrivTextSliceB
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivTextSliceBSlice = prismic.SharedSlice<
  "priv_text_slice_b",
  PrivTextSliceBSliceVariation
>;

/**
 * Primary content in *PrivTitleSlice → Primary*
 */
export interface PrivTitleSliceSliceDefaultPrimary {
  /**
   * Title field in *PrivTitleSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: priv_title_slice.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for PrivTitleSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivTitleSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrivTitleSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrivTitleSlice*
 */
type PrivTitleSliceSliceVariation = PrivTitleSliceSliceDefault;

/**
 * PrivTitleSlice Shared Slice
 *
 * - **API ID**: `priv_title_slice`
 * - **Description**: PrivTitleSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivTitleSliceSlice = prismic.SharedSlice<
  "priv_title_slice",
  PrivTitleSliceSliceVariation
>;

/**
 * Default variation for VerticalImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VerticalImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *VerticalImages*
 */
type VerticalImagesSliceVariation = VerticalImagesSliceDefault;

/**
 * VerticalImages Shared Slice
 *
 * - **API ID**: `vertical_images`
 * - **Description**: VerticalImages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VerticalImagesSlice = prismic.SharedSlice<
  "vertical_images",
  VerticalImagesSliceVariation
>;

/**
 * Primary content in *Vision → Primary*
 */
export interface WorkChildBriefSliceDefaultPrimary {
  /**
   * Description field in *Vision → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_brief.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Client field in *Vision → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_brief.primary.client
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  client: prismic.RichTextField;

  /**
   * Sector field in *Vision → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_brief.primary.sector
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sector: prismic.RichTextField;

  /**
   * Status field in *Vision → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_brief.primary.status
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  status: prismic.RichTextField;

  /**
   * Location field in *Vision → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_brief.primary.location
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  location: prismic.RichTextField;

  /**
   * Scope field in *Vision → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_brief.primary.scope
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  scope: prismic.RichTextField;

  /**
   * Scale field in *Vision → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_brief.primary.scale
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  scale: prismic.RichTextField;

  /**
   * Text Left field in *Vision → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_brief.primary.text_left
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_left: prismic.RichTextField;
}

/**
 * Default variation for Vision Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkChildBriefSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkChildBriefSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Vision*
 */
type WorkChildBriefSliceVariation = WorkChildBriefSliceDefault;

/**
 * Vision Shared Slice
 *
 * - **API ID**: `work_child_brief`
 * - **Description**: WorkChildBrief
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkChildBriefSlice = prismic.SharedSlice<
  "work_child_brief",
  WorkChildBriefSliceVariation
>;

/**
 * Primary content in *WorkChildHero → Primary*
 */
export interface WorkChildHeroSliceDefaultPrimary {
  /**
   * Image field in *WorkChildHero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *WorkChildHero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for WorkChildHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkChildHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkChildHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WorkChildHero*
 */
type WorkChildHeroSliceVariation = WorkChildHeroSliceDefault;

/**
 * WorkChildHero Shared Slice
 *
 * - **API ID**: `work_child_hero`
 * - **Description**: WorkChildHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkChildHeroSlice = prismic.SharedSlice<
  "work_child_hero",
  WorkChildHeroSliceVariation
>;

/**
 * Primary content in *WorkChildImage → Primary*
 */
export interface WorkChildImageSliceDefaultPrimary {
  /**
   * Image field in *WorkChildImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for WorkChildImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkChildImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkChildImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WorkChildImage*
 */
type WorkChildImageSliceVariation = WorkChildImageSliceDefault;

/**
 * WorkChildImage Shared Slice
 *
 * - **API ID**: `work_child_image`
 * - **Description**: WorkChildImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkChildImageSlice = prismic.SharedSlice<
  "work_child_image",
  WorkChildImageSliceVariation
>;

/**
 * Primary content in *WorkChildVision → Primary*
 */
export interface WorkChildVisionSliceDefaultPrimary {
  /**
   * Title field in *WorkChildVision → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_vision.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *WorkChildVision → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_child_vision.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for WorkChildVision Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkChildVisionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkChildVisionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WorkChildVision*
 */
type WorkChildVisionSliceVariation = WorkChildVisionSliceDefault;

/**
 * WorkChildVision Shared Slice
 *
 * - **API ID**: `work_child_vision`
 * - **Description**: WorkChildVision
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkChildVisionSlice = prismic.SharedSlice<
  "work_child_vision",
  WorkChildVisionSliceVariation
>;

/**
 * Primary content in *WorksShowcaseLeft → Primary*
 */
export interface WorksShowcaseLeftSliceDefaultPrimary {
  /**
   * Company Name A field in *WorksShowcaseLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_left.primary.company_name_a
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_name_a: prismic.RichTextField;

  /**
   * Description A field in *WorksShowcaseLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_left.primary.description_a
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_a: prismic.RichTextField;

  /**
   * Image A field in *WorksShowcaseLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_left.primary.image_a
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_a: prismic.ImageField<never>;

  /**
   * CTA Link A field in *WorksShowcaseLeft → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_left.primary.cta_link_a
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link_a: prismic.LinkField;

  /**
   * Company Name B field in *WorksShowcaseLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_left.primary.company_name_b
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_name_b: prismic.RichTextField;

  /**
   * Description B field in *WorksShowcaseLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_left.primary.description_b
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_b: prismic.RichTextField;

  /**
   * Image B field in *WorksShowcaseLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_left.primary.image_b
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_b: prismic.ImageField<never>;

  /**
   * CTA Link B field in *WorksShowcaseLeft → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_left.primary.cta_link_b
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link_b: prismic.LinkField;

  /**
   * Company Name C field in *WorksShowcaseLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_left.primary.company_name_c
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_name_c: prismic.RichTextField;

  /**
   * Description C field in *WorksShowcaseLeft → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_left.primary.description_c
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_c: prismic.RichTextField;

  /**
   * Image C field in *WorksShowcaseLeft → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_left.primary.image_c
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_c: prismic.ImageField<never>;

  /**
   * CTA Link C field in *WorksShowcaseLeft → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_left.primary.cta_link_c
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link_c: prismic.LinkField;
}

/**
 * Default variation for WorksShowcaseLeft Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksShowcaseLeftSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorksShowcaseLeftSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WorksShowcaseLeft*
 */
type WorksShowcaseLeftSliceVariation = WorksShowcaseLeftSliceDefault;

/**
 * WorksShowcaseLeft Shared Slice
 *
 * - **API ID**: `works_showcase_left`
 * - **Description**: WorksShowcaseLeft
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksShowcaseLeftSlice = prismic.SharedSlice<
  "works_showcase_left",
  WorksShowcaseLeftSliceVariation
>;

/**
 * Primary content in *WorksShowcaseRight → Primary*
 */
export interface WorksShowcaseRightSliceDefaultPrimary {
  /**
   * Company Name A field in *WorksShowcaseRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_right.primary.company_name_a
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_name_a: prismic.RichTextField;

  /**
   * Description A field in *WorksShowcaseRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_right.primary.description_a
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_a: prismic.RichTextField;

  /**
   * Image A field in *WorksShowcaseRight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_right.primary.image_a
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_a: prismic.ImageField<never>;

  /**
   * CTA Link A field in *WorksShowcaseRight → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_right.primary.cta_link_a
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link_a: prismic.LinkField;

  /**
   * Company Name B field in *WorksShowcaseRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_right.primary.company_name_b
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_name_b: prismic.RichTextField;

  /**
   * Description B field in *WorksShowcaseRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_right.primary.description_b
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_b: prismic.RichTextField;

  /**
   * Image B field in *WorksShowcaseRight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_right.primary.image_b
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_b: prismic.ImageField<never>;

  /**
   * CTA Link B field in *WorksShowcaseRight → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_right.primary.cta_link_b
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link_b: prismic.LinkField;

  /**
   * Company Name C field in *WorksShowcaseRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_right.primary.company_name_c
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company_name_c: prismic.RichTextField;

  /**
   * Description C field in *WorksShowcaseRight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_right.primary.description_c
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_c: prismic.RichTextField;

  /**
   * Image C field in *WorksShowcaseRight → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_right.primary.image_c
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_c: prismic.ImageField<never>;

  /**
   * CTA Link C field in *WorksShowcaseRight → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: works_showcase_right.primary.cta_link_c
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link_c: prismic.LinkField;
}

/**
 * Default variation for WorksShowcaseRight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksShowcaseRightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorksShowcaseRightSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WorksShowcaseRight*
 */
type WorksShowcaseRightSliceVariation = WorksShowcaseRightSliceDefault;

/**
 * WorksShowcaseRight Shared Slice
 *
 * - **API ID**: `works_showcase_right`
 * - **Description**: WorksShowcaseRight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorksShowcaseRightSlice = prismic.SharedSlice<
  "works_showcase_right",
  WorksShowcaseRightSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PrivacyPolicyDocument,
      PrivacyPolicyDocumentData,
      PrivacyPolicyDocumentDataSlicesSlice,
      WorksDocument,
      WorksDocumentData,
      WorksDocumentDataSlicesSlice,
      WorksChildDocument,
      WorksChildDocumentData,
      WorksChildDocumentDataSlicesSlice,
      AllDocumentTypes,
      BehindTheScenesSlice,
      BehindTheScenesSliceDefaultPrimary,
      BehindTheScenesSliceDefaultItem,
      BehindTheScenesSliceVariation,
      BehindTheScenesSliceDefault,
      ContactShowcaseSlice,
      ContactShowcaseSliceDefaultPrimary,
      ContactShowcaseSliceDefaultItem,
      ContactShowcaseSliceVariation,
      ContactShowcaseSliceDefault,
      FeaturedWorksShowCaseSlice,
      FeaturedWorksShowCaseSliceDefaultPrimary,
      FeaturedWorksShowCaseSliceDefaultItem,
      FeaturedWorksShowCaseSliceVariation,
      FeaturedWorksShowCaseSliceDefault,
      FeaturedWorksTitleSlice,
      FeaturedWorksTitleSliceDefaultPrimary,
      FeaturedWorksTitleSliceVariation,
      FeaturedWorksTitleSliceDefault,
      HomeBriefSlice,
      HomeBriefSliceDefaultPrimary,
      HomeBriefSliceVariation,
      HomeBriefSliceDefault,
      HomeHeroSlice,
      HomeHeroSliceDefaultPrimary,
      HomeHeroSliceVariation,
      HomeHeroSliceDefault,
      MarqueeSliceSlice,
      MarqueeSliceSliceDefaultPrimary,
      MarqueeSliceSliceDefaultItem,
      MarqueeSliceSliceVariation,
      MarqueeSliceSliceDefault,
      NewsAndInsightsSlice,
      NewsAndInsightsSliceDefaultPrimary,
      NewsAndInsightsSliceDefaultItem,
      NewsAndInsightsSliceVariation,
      NewsAndInsightsSliceDefault,
      NextProjectLinkSlice,
      NextProjectLinkSliceDefaultPrimary,
      NextProjectLinkSliceVariation,
      NextProjectLinkSliceDefault,
      PrivSubTitleSliceSlice,
      PrivSubTitleSliceSliceDefaultPrimary,
      PrivSubTitleSliceSliceVariation,
      PrivSubTitleSliceSliceDefault,
      PrivTextSliceSlice,
      PrivTextSliceSliceDefaultPrimary,
      PrivTextSliceSliceVariation,
      PrivTextSliceSliceDefault,
      PrivTextSliceASlice,
      PrivTextSliceASliceDefaultPrimary,
      PrivTextSliceASliceVariation,
      PrivTextSliceASliceDefault,
      PrivTextSliceBSlice,
      PrivTextSliceBSliceDefaultPrimary,
      PrivTextSliceBSliceVariation,
      PrivTextSliceBSliceDefault,
      PrivTitleSliceSlice,
      PrivTitleSliceSliceDefaultPrimary,
      PrivTitleSliceSliceVariation,
      PrivTitleSliceSliceDefault,
      VerticalImagesSlice,
      VerticalImagesSliceVariation,
      VerticalImagesSliceDefault,
      WorkChildBriefSlice,
      WorkChildBriefSliceDefaultPrimary,
      WorkChildBriefSliceVariation,
      WorkChildBriefSliceDefault,
      WorkChildHeroSlice,
      WorkChildHeroSliceDefaultPrimary,
      WorkChildHeroSliceVariation,
      WorkChildHeroSliceDefault,
      WorkChildImageSlice,
      WorkChildImageSliceDefaultPrimary,
      WorkChildImageSliceVariation,
      WorkChildImageSliceDefault,
      WorkChildVisionSlice,
      WorkChildVisionSliceDefaultPrimary,
      WorkChildVisionSliceVariation,
      WorkChildVisionSliceDefault,
      WorksShowcaseLeftSlice,
      WorksShowcaseLeftSliceDefaultPrimary,
      WorksShowcaseLeftSliceVariation,
      WorksShowcaseLeftSliceDefault,
      WorksShowcaseRightSlice,
      WorksShowcaseRightSliceDefaultPrimary,
      WorksShowcaseRightSliceVariation,
      WorksShowcaseRightSliceDefault,
    };
  }
}
