// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  behind_the_scenes: dynamic(() => import("./BehindTheScenes")),
  contact_showcase: dynamic(() => import("./ContactShowcase")),
  featured_works_show_case: dynamic(() => import("./FeaturedWorksShowCase")),
  featured_works_title: dynamic(() => import("./FeaturedWorksTitle")),
  home_brief: dynamic(() => import("./HomeBrief")),
  home_hero: dynamic(() => import("./HomeHero")),
  marquee_slice: dynamic(() => import("./MarqueeSlice")),
  news_and_insights: dynamic(() => import("./NewsAndInsights")),
  next_project_link: dynamic(() => import("./NextProjectLink")),
  priv_sub_title_slice: dynamic(() => import("./PrivSubTitleSlice")),
  priv_text_slice: dynamic(() => import("./PrivTextSlice")),
  priv_text_slice_a: dynamic(() => import("./PrivTextSliceA")),
  priv_text_slice_b: dynamic(() => import("./PrivTextSliceB")),
  priv_title_slice: dynamic(() => import("./PrivTitleSlice")),
  vertical_images: dynamic(() => import("./VerticalImages")),
  work_child_brief: dynamic(() => import("./Vision")),
  work_child_hero: dynamic(() => import("./WorkChildHero")),
  work_child_image: dynamic(() => import("./WorkChildImage")),
  work_child_vision: dynamic(() => import("./WorkChildVision")),
  works_showcase_left: dynamic(() => import("./WorksShowcaseLeft")),
  works_showcase_right: dynamic(() => import("./WorksShowcaseRight")),
};
